---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workloadsapi-secret
  namespace: workloadsapi
spec:
  encryptedData:
    ConnectionStrings__WorkloadsModule: AgBNG8St1p8irxH8ojN9M6DzvV1L4VE4yyFH6bObNPztJxEHMFVV/yOkoU2DC0XeHYFC5Wx8Oj8t96Hkln2rRQFPWhVrE4uK9fgOZAk5o2WZti8CfQfRcpkKXJ0xoX5oE6CXLjDUjO073JWoRJcD8AN9xj9xVZaPcgkdZyBmQlajAjhW78sS+5gyVsR2f44NihkEO3nNy9FGFRe54Bjt6fTq9IHNGUteJEkDqHSjUfzaIMg90p3FHm9U/RS19WolqemyAgcDZkRD47Akzlhj17zGTJkMVgl09swRcvQLfvV9cT5izNIpP4jUPvi6hFfHmHOliIb21u9GWFZ+ozIBNXwKxc6uV6FotbQwwZk4LARJ2MQT9CXC9MMLvNtFMq3y8Dy4t/N1DnMSU72/W2/e73P+Zp+2LoJshrELsjsTlb0Ivkpyzj3TtRX9qPbnpr7OkKP9/Ixm7PFwbZYs+XBm1a4hCn4yRthn34Y9Uprh+GFzvvXv5tBpYSklIv/6up9gGqHhS04V6dmyVwZ6zTuiuDY6ywQK6UHbMrlvGZhcxVkrUzu8+LhO2WNpPw7mM0Iu0cs03fed03k5SedLhquDqRsbQ3HBb4AnBSI/R7QN+F3gBxkxCXDHa9xK+52d1cNesNCL6TnnxHj+K+STJgYdE6aDwdRz3i4qA7HhEsiXF0pznjCka6je/WvaJ5LeMb+GmJRTZTVbxzCtL9q8DeAocQUt4x7FCTHLmGWXIo/LkkF2jhfYWspPJjPlFTanHQC+Uc/3Rvt9XTgaeiSnu5ZSmlkB88CYZLSZy0/BGWQqdoLz5D+70uIxOw==
  template:
    metadata:
      name: workloadsapi-secret
      namespace: workloadsapi
