{{- if and .Values.configMap.enabled (ne .Values.applicationType "angular-spa") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- if eq .Values.applicationType "dotnet-webapi" }}
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  {{- else if eq .Values.applicationType "dotnet-worker" }}
  DOTNET_ENVIRONMENT: "Production"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  {{- end }}
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}




