---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: customersapi-secret
  namespace: customersapi
spec:
  encryptedData:
    ConnectionStrings__CustomersModule: AgBfufoshb+yV4HRvnxS1sRga/SYoGIiCA8odpVGwH082kG5UijHI2+hngz2s80AQNtXsa2O9wb15P/sJXdpz3jjV2hBvsHATBkxLy58kS9prJWxyaXmngltlrc3UTPfCoYshXcCguZzxqxVPiHVLKkpOBKo5pKrDsxky2cAe4gtPCHLEAZ2gWJ+TPSuI27+4KAz5ORYpv8V6G1/jjVrvOm/ry2s671pC+uHKhkug0gq11me+xaY8uxCmllwvv1lrGfsGUgrvUSek4iixPFmj/7yUykUiGPgWoOCt+9GUU0G8fGIhbatq+csSBevIkvQRJCUJo033OAYJJqLqZbiSpPIYMM/YFwFvk7gQfiTroOgXx51SO5AMQWUctNuc1cgttG+BwdRjFLsEAx482HDQhGzVMOfryA/dPtGDvojfByhC/wPT7KVxJSJUrAu81o5aI9s1JpL7f+accFQLGyET7lZvx0U30YUMG2PNhP5leOjftKnARHWbH7zhHKElX9stn3m9hgrqpmSgIq893cUqKNJgLVUmJMc7X217/gxu+r427LG0cpBOEzmGZ4uK/2rUzZwVKTAyUK1tKC9tQ7jHTbDjDV850AjMPNhQgJhnjT3nkI/s8M5OV/a1it2jNfbD28MupMc7HmmzJDEhj87gmxb/uWqexkAx1PpVD31e9zsgCKiUCZH4XxHhrBp7jqxmSnC6JZAFtIeMTd+0KaTFJ8BG6RnJ6BXA7GGopiXO1Tt/znGpbAkHXRqPIIM9Z7je861Pn8yrpXmCqID06aPkf3OO0HD6L970F8z5KbUs4nGkyC8Z8+rgA==
  template:
    metadata:
      name: customersapi-secret
      namespace: customersapi
